### ISSUE TITLE
Merge ptokax scripts into this repository itself

### ISSUE THREAD

**Issue by proffapt** [proffapt/Metahub#8]
- [ ] Add ptokax scripts into this same repo by default
- [ ] Remove scripts cloning part from `ptokax-setup.sh`

**Comment by shikharish** [comment]
Will work on this.
Can you please explain the issue a bit?

**Comment by proffapt** [comment]
https://github.com/proffapt/Metahub/blob/c632f4f0a239c2272978151b19cdd8d92bf6f080/ptokax-setup.sh#L129

No need to do this in setup file.
Remove this step and instead merge the repo being cloned in this step in this repository in same location.
